### ISSUE TITLE
Показывает не правильно маршрут

### ISSUE THREAD

**Issue by papaiegoriminecraft** [KostyanSigaev/Micro-Trolleybus_Simulator_bugtracker#1]
Ехал по 4 маршруту. И вижу, то что мне показывает ещё и 5 маршрут. Не знаю, должно так быть или нет. Карта была Старый Город Зима. На карте Старый Город Лето не пробовал.
Лог файл: 
[MTS.log](https://github.com/user-attachments/files/15570062/MTS.log)
Чтобы воспроизвести этот баг (если это баг) то 1: Надо поставить троллейбус 683 (необязательно именно этот троллейбус (наверно)) 2: поставить перекраску (необязательно ставить перекраску). 3: Надо поставить его на 4 маршрут. 4: Доехать до места который на скриншоте.
Я ожидал увидеть на скриншоте только маршрут который ведёт на лево, а показывает ещё маршрут и на право
![Screenshot_2024-06-04-23-14-28-310_pub SoprotivlenieBespolezno MTS](https://github.com/KostyanSigaev/Micro-Trolleybus_Simulator_bugtracker/assets/115942396/9b346148-10ac-4102-aa66-6c0044130dc9)

**Comment by KostyanSigaev** [comment]
Знаю, уже исправил
