### ISSUE TITLE
Не показывает когда занято начало маршрута

### ISSUE THREAD

**Issue by papaiegoriminecraft** [KostyanSigaev/Micro-Trolleybus_Simulator_bugtracker#2]
Не показывает когда занято начало 2 маршрута. Также и с маршрутом 2а. Баг происходит на карте Старый Город Зима, на карте Старый Город Лето не пробовал.
![Screenshot_2024-06-04-23-42-06-736_pub SoprotivlenieBespolezno MTS](https://github.com/KostyanSigaev/Micro-Trolleybus_Simulator_bugtracker/assets/115942396/2509978a-dfef-42be-a33c-bd2e3dffb929)
Лог файл: 
[MTS.log](https://github.com/user-attachments/files/15570269/MTS.log)
Чтобы воспроизвести баг надо сделать: 1: Поставить новый троллейбус 683 (необязательно этот троллейбус). 2: поставить перекраску (необязательно ставить перекраску). 3: поставить троллейбус на 2 либо 2а маршрут.
Я ожидал то что будет написано что начало маршрута занято, а оно пишет то что начало маршрута свободно.

**Comment by KostyanSigaev** [comment]
Принял, буду проверять

**Comment by papaiegoriminecraft** [comment]
> Принял, буду проверять
Баг есть или нет?

**Comment by KostyanSigaev** [comment]
> > Баг есть или нет?

Да, я заметил, но пока не понятно, почему проверка в коде не работает...

**Comment by papaiegoriminecraft** [comment]
> > > Баг есть или нет?
> 
> Да, я заметил, но пока не понятно, почему проверка в коде не работает...

Ок

**Comment by KostyanSigaev** [comment]
Вроде как исправил, но не уверен. Сейчас у меня всё работает корректно, но с учётом того, как обычно после выпуска обновления всё ломается, пока решенным отмечать не буду, мало ли...

**Comment by papaiegoriminecraft** [comment]
> Вроде как исправил, но не уверен. Сейчас у меня всё работает корректно, но с учётом того, как обычно после выпуска обновления всё ломается, пока решенным отмечать не буду, мало ли...

Ок

**Comment by papaiegoriminecraft** [comment]
Вроде баг все ещё есть

**Comment by KostyanSigaev** [comment]
У меня этот баг появляется крайне редко и только, когда низкий FPS

**Comment by KostyanSigaev** [comment]
Даже сейчас этот странный баг всё ещё на месте...

**Comment by KostyanSigaev** [comment]
Вот теперь точно исправлено...
