### ISSUE TITLE
Не подключаются штанги

### ISSUE THREAD

**Issue by papaiegoriminecraft** [KostyanSigaev/Micro-Trolleybus_Simulator_bugtracker#3]
Если поставить троллейбус 682Г СМЕ на маршрут 1 либо 4 то тогда штанги не подключается к проводам. Карта: Старый Город Зима. На Старый Город Лето не пробовал.
![Screenshot_2024-06-10-11-01-04-656_pub SoprotivlenieBespolezno MTS](https://github.com/KostyanSigaev/Micro-Trolleybus_Simulator_bugtracker/assets/115942396/feb8d447-6f63-463b-8d28-433528feac93)
Лог файл: 
[MTS.log](https://github.com/user-attachments/files/15811246/MTS.log)
Чтобы воспроизвести баг нужно: 1: Заспавнить троллейбус 682Г СМЕ. 2: Поставить его на маршрут 1 либо 4.
Я ожидал что троллейбус присоединиться к проводам и поедет, а он не подключается к ним. 
Кстати, часто этот троллейбус на маршрутах шатает либо он вообще куда-то улетает если ехать самостоятельно, не на ИИ.

**Comment by KostyanSigaev** [comment]
Эта проблема связана с тем, что штанги не могут найти нужный провод на стыке проводов, а у 682Г СМЕ штанги равно туда и цепляются. Я уже пробовал перемещать место начала, но тогда у других сочленённых троллейбусов возникнут проблемы в этом же месте. Сейчас в разработке находится улучшенная механика штанг, уже в следующем обновлении её можно будет включить в настройках, с ней штанги правильно находят провода и подключаются, но пока эта механика остаётся экспериментальной потому что штанги могут на ровном месте слететь...

**Comment by papaiegoriminecraft** [comment]
Хорошо, спасибо
