### ISSUE TITLE
Не переходит в главное меню

### ISSUE THREAD

**Issue by papaiegoriminecraft** [KostyanSigaev/Micro-Trolleybus_Simulator_bugtracker#4]
Когда я нажимаю кнопку главное меню на картах НСК и Старый Зимний Город, то тогда оно не выходит в главное меню, а просто троллейбусы на заднем фоне начинают ехать.
![Screenshot_2024-06-15-11-26-08-906_pub SoprotivlenieBespolezno MTS](https://github.com/KostyanSigaev/Micro-Trolleybus_Simulator_bugtracker/assets/115942396/5b9adc29-3006-459e-8cd0-4af968ce0aed)
Лог файл: 
[MTS.log](https://github.com/user-attachments/files/15846261/MTS.log)
Чтобы воспроизвести баг, нужно: 1: Зайти на карту Старый Зимний Город, либо на НСК. 2: Нужно зайти в меню и нажать кнопку: Главное Меню.
Я ожидал, то что я просто выйду в главное меню. А происходит так, то что меня не перекидывает в меню, а троллейбусы на заднем фоне начинают ездить.

**Comment by KostyanSigaev** [comment]
Да, я проверил, есть такой баг, сразу же исправил.
