### ISSUE TITLE
Баг со случайными перекрасками

### ISSUE THREAD

**Issue by Damirus2077** [KostyanSigaev/Micro-Trolleybus_Simulator_bugtracker#8]
При установке стандартных перекрасок через игру на Android 10 (по поводу других не знаю) не работают случайные перекраски, несмотря на включенный пункт в настройках

**Comment by KostyanSigaev** [comment]
Хорошее наблюдение! Я совсем забыл за систему случайных перекрасок, потому при обновлении кода путей попросту забыл за них. Если я правильно описал проблему, то если разместить перекраски по последнему пути, на котором перекраски использовались до обновления, то всё заработает, если, конечно же, игра не была переустановлена...

**Comment by Damirus2077** [comment]
> Хорошее наблюдение! Я совсем забыл за систему случайных перекрасок, потому при обновлении кода путей попросту забыл за них. Если я правильно описал проблему, то если разместить перекраски по последнему пути, на котором перекраски использовались до обновления, то всё заработает, если, конечно же, игра не была переустановлена...

**Comment by Damirus2077** [comment]
> Если я правильно описал проблему, то если разместить перекраски по последнему пути, на котором перекраски использовались до обновления, то всё заработает, если, конечно же, игра не была переустановлена...

Почему-то в настройках игры пропала функция изменения пути файлов, это из-за обновления или просто я тупой? (С вероятностью 99% второе)))

**Comment by KostyanSigaev** [comment]
> настройках игры пропала функция изменения пути файлов

Я её удалил, с ней возникали некоторые проблемы, теперь путь только один.

**Comment by KostyanSigaev** [comment]
Только что исправил
